### ISSUE TITLE
Allow Q&A only into some categories

### ISSUE THREAD

**Issue by Benderwan** [NodeBB/nodebb-plugin-question-and-answer#21]
Hey there !

This is nothing important but it would be great if we could allow users to post questions only when they are into some categories where it would be default !

Have a nice day

**Comment by whittssg** [comment]
The latest version has this as an option but it doesn't help me much since it doesnt allow you to select multiple categories - either all categories have it by default or just one.. I have a category with around 15 sub categories and i needed this option in all of them - any way to make it either multi-select or make it so that it auto selects sub categories as well.? Thanks

**Comment by whittssg** [comment]
Can we set the dropdown in the admin settings to multiselect add then store the category ids as an array to the settings:question-and-answer object? Then when you query the settings:question-and-answer object loop through the array to get the category ids that should be set to default?

**Comment by 1ns** [comment]
This is a good idea. My actual forum have 3 categories for answers (Specific to my portal, animes and docs) and this upgrade will solve my problem.

**Comment by exomarty** [comment]
can we have this @julianlam ? this is usefull for help and support subforum but not all categories

**Comment by psychobunny** [comment]
Cleaning up old issues; this is an option in the latest version
